import "./globals.css";

export const metadata = {
  title: "Sunil - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body
        className="antialiased leading-8 overflow-x-hidden"
        suppressHydrationWarning={true}
      >
        <link 
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&family=Ovo&display=swap" 
          rel="stylesheet" 
        />
        {children}
      </body>
    </html>
  );
}
